spring:
  application:
    name: Spring Boot Project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kkp_msib6
    username: root
    password: starsyndrome

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: fpbejfejs1@gmail.com
    password: dqkl iopa omlw spxz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

module-name: Metrodata Academy
api-version: 1.0.0